name: Build and deploy Node.js app to Azure Web App - Zoe-InternationalMinistry

on:
  push:
    branches:
      - Local-Branch
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4  # Use the latest version of setup-node
        with:
          node-version: '20.x'  # Specify the Node.js version

      # Install dependencies and build the application
      - name: Build
        run: |
          npm install
          npm run build

      # Log the contents of the build directory
      - name: List build directory contents
        run: |
          dir ./build  # Use 'ls -R' for Linux runners

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./build  # Specify the build directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./build  # Ensure this matches the upload path

      # Clean up any old deployment files
      - name: Clean up old deployment files
        run: |
          if [ -d "/tmp/zipdeploy" ]; then 
            rm -rf /tmp/zipdeploy/*; 
          fi
        shell: bash

      # Set Azure Cloud
      - name: Set Azure Cloud
        run: az cloud set -n AzureCloud  # Ensure AzureCloud is set

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2  # Use the latest version of azure/login
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}
          auth-type: "SERVICE_PRINCIPAL"  # Ensure 'SERVICE_PRINCIPAL' is used for login

      # Debug subscription details to verify access
      - name: List Azure Subscriptions
        run: az account list --output table

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Zoe-InternationalMinistry'
          package: './build'  # Path to the downloaded artifact directory